apiVersion: apps/v1
kind: Deployment
metadata:
  name: ep-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ep-demo
  template:
    metadata:
      labels:
        app: ep-demo
    spec:
      containers:
        - name: ep-demo
          image: ngocvd4/ep-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
