apiVersion: v1
kind: Service
metadata:
  name: ep-demo-service
spec:
  type: NodePort
  selector:
    app: ep-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30080
